version: '3.8'

services:
  # --- Service 1 : InfluxDB (Base de donn√©es) ---
  influxdb:
    image: influxdb:2.7
    container_name: bin_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=waste_management
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  fusion-service:
    build: .
    container_name: bin_fusion_service
    ports:
      - "8001:8001"
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=waste_management
    restart: on-failure

volumes:
  influxdb_data:
  influxdb_config: