services:
  mosquitto-cloud:
    image: eclipse-mosquitto
    container_name: mosquitto-cloud
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1884:1884"
    networks:
      - cloud_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cloud_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cloud_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - cloud_net

  bridge-mqtt-kafka:
    build:
      context: ./bridgeMqttToKafka
      dockerfile: Dockerfile
    container_name: bridge-mqtt-kafka
    depends_on:
      - mosquitto-cloud
      - kafka
    environment:
      - MQTT_BROKER=mosquitto-cloud
      - KAFKA_SERVER=kafka:29092
    networks:
      - cloud_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - cloud_net

  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    command: "osrm-routed --algorithm mld /data/map.osrm"
    volumes:
      - ./osrm-data:/data
    networks:
      - cloud_net

  vrp-service:
    build: ./serviceVrp
    container_name: vrp-service
    depends_on:
      - osrm-backend
    environment:
      - OSRM_URL=http://osrm-backend:5000
    networks:
      - cloud_net

  aggregator-service:
    build: ./serviceAggregator
    container_name: aggregator-service
    depends_on:
      - kafka
      - vrp-service
      - mongodb
    environment:
      - KAFKA_BROKER=kafka:29092
      - VRP_URL=http://vrp-service:8000/solve_vrp
      - TRUCK_URL=http://truck-api:5000/api/trucks
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - cloud_net

networks:
  cloud_net:
    name: waste_network
    driver: bridge

volumes:
  mongodb_data: